name = "Age of Rebellion"
author = "DartRuffian"
prefix = "aor"
mainprefix = "z"

[version]
path = "addons/main/script_version.hpp"
git_hash = 0

[files]
include = ["mod.cpp", "logo_AOR.png", "logo_AOR_ca.paa", "LICENSE", "README.md"]
exclude = ["*.spp", "*.spp.painter_lock", "*.psd", "fnc_empty.sqf"]

[properties]
author = "DartRuffian"
url = "https://github.com/DartsArmaMods/AgeOfRebellion"
